discovery:
  exclusions:
  - venv
engine:
  runtime: pytest
  load-pytest-plugins: true
  cpu-cores: 4
env:
  PYTHONPATH: src
  DJANGO_SETTINGS_MODULE: config.settings.local
  DJANGO_ALLOW_ASYNC_UNSAFE: "true"
